### ISSUE TITLE
Direct page links

### ISSUE THREAD

**Issue by NotGovernor** [secure-77/Perlite#90] opened 2023-06-01 01:38 UTC
Is there a way to, instead of relative paths to internal links, we can do an absolute path from root?

EX:
Instead of the following to navigate up and then back down the folder structure: 
```
[[.../.../Folder/File]]
```

We could just do this and it would work from wherever this link existed in the site hierarchy:
```
[[/Folder/File]]
```

**Comment by secure-77** [comment] 2023-07-27 15:56
I will take a look at this

**Comment by secure-77** [comment] 2024-01-11 00:24
I spend some hours into this topic and tried to support both cases, even if they are mixed in one environment. Unfortunately there is one edge case which I can't manage.

If you have a file (via relative file name) in one folder it will look like this

`![[Pasted image 20240111010137.png]]`

The problem is, files located in the root folder will look like the same so I can't decide if i need to link to the same folder or the root folder.

The only option I see is to implement a setting (variable) to switch between relative and absolute file links.

**Comment by secure-77** [comment] 2024-01-12 16:34
its implemented on the dev branch and will be included in the next release. There will be a new setting `ABSOLUTE_PATHES`

**Comment by secure-77** [comment] 2024-01-14 15:48
fixed / implemented in 1.5.8

**Comment by secure-77** [comment] 2024-02-08 10:57
there is a little bug in the 1.5.8, its already fixed in the dev version and will be in the next release

**Comment by NotGovernor** [comment] 2024-04-04 21:18
Thanks! Sorry for me not checking my notifications for so long. I see this has already been implimented, so awesome!

Had I not been tardy I would have responded as follows:

> The problem is, files located in the root folder will look like the same so I can't decide if i need to link to the same folder or the root folder.

I would have it only look for such a file in the current local folder. If the user wants to reference something in the root they could just do a `/image.png`

Just my 2 cents. :) Thanks for your work on this.

**Comment by secure-77** [comment] 2024-09-24 09:40
implemented in release [1.5.9](https://github.com/secure-77/Perlite/releases/tag/1.5.9)

**Closed by secure-77** 2024-09-24 09:40 UTC
Labels: enhancement, on dev
