### ISSUE TITLE
Support renaming links

### ISSUE THREAD

**Issue by gigibu5** [secure-77/Perlite#10] opened 2022-03-18 20:50 UTC
In Obsidian, there is an option to rename internal links:
```
[[Linked file|New name]]
```
The delimiter is the `|` symbol. 

I can implement the feature myself, you just need to tell me, where in the source code you parse links.

Thank you

**Comment by secure-77** [comment] 2022-03-18 23:25
Hey @gigibu5,

Thanks for the issue, the code should now handle also custom named links. Please take a look a the latest commit of the content.php (1.4.2 RC) https://github.com/secure-77/Perlite/commit/0c1e760590c6388ef7e0dfef8cb134cc2316baf2
and let me know if this works for you.

Thank you!

**Comment by gigibu5** [comment] 2022-03-19 07:58
It works great, thank you. 

I have another unrelated problem. Some of my MD file's don't want to open for some reason? 
For example http://wiki.zigakralj.com/?link=%2FLinux%2FApache%2FReverse%20proxy opens fine
But http://wiki.zigakralj.com/?link=%2FLinux%2FApache%2FLastni%20certifikati dosen't open.

Sorry for the Slovenian language :)

**Comment by gigibu5** [comment] 2022-03-19 07:59
I have also implemented the change of the URL, when you click on a seperate file in the menu:

Addition in perlite.js
```js
function changeURL(str){
  window.history.pushState({},"", "/?link="+str);
  getContent(str);
}
```
Change in helper.php -> menu function
```php
$html .= '		<li>
                                    <a href="#" onclick=changeURL("'. $pathClean .'"); id="'. $pathID .'" class="perlite-link">'. $mdFile .'</a>
                                </li>';
```

**Comment by secure-77** [comment] 2022-03-20 08:37
> It works great, thank you.
> 
> I have another unrelated problem. Some of my MD file's don't want to open for some reason? For example http://wiki.zigakralj.com/?link=%2FLinux%2FApache%2FReverse%20proxy opens fine But http://wiki.zigakralj.com/?link=%2FLinux%2FApache%2FLastni%20certifikati dosen't open.
> 
> Source MD files are available here: http://wiki.zigakralj.com/Wiki
> 
> Sorry for the Slovenian language :)
Glad the custom links are now working!

Regarding your problem: I cant reproduce it, i downloaded the folder and files and for me this is working.

![image](https://user-images.githubusercontent.com/31564517/159154311-5d76d93c-1ca9-4690-b616-0ded392f5e76.png)

In the console I only can see that there is server error 500 from PHP in your instance, so maybe the PHP engine cant access the file or something else is wrong. 

I only can suggest you to check the php error log to figure out, what exactly is the problem. Maybe also one of the following steps can help you to narrow down the problem:

- make sure you have installed the mb_strings php plugin
- check the permissions of the file, make sure the php engine has access to it  
- try to change the filename and see what happens
- try to change the content and see what happens


Regarding the url change, this is a great idea, i will create a new Issue for this and will implamte this in the next release
Thanks for that!

**Comment by secure-77** [comment] 2022-03-20 08:42
@gigibu5 If you still need support for your server problem, please create a new issue for this, i will close this one.

**Closed by secure-77** 2022-03-20 08:42 UTC
Labels: enhancement, implemented / fixed
