### ISSUE TITLE
attachments are loaded if in the root folder, otherwise ignored

### ISSUE THREAD

**Issue by knikhil42** [secure-77/Perlite#61] opened 2023-02-18 07:27 UTC
attachments are loaded if in the root folder, otherwise ignored

<img width="360" alt="Screenshot 2023-02-18 at 12 42 11 PM" src="https://user-images.githubusercontent.com/84435819/219847515-2f04d772-bfc0-4862-8c52-c94db2065801.png">

<img width="986" alt="Screenshot 2023-02-18 at 12 41 53 PM" src="https://user-images.githubusercontent.com/84435819/219847512-ec4ead52-42ca-4f7b-a5e1-e262a4ac8db0.png">

<img width="347" alt="Screenshot 2023-02-18 at 12 42 26 PM" src="https://user-images.githubusercontent.com/84435819/219847516-863aeacc-b35b-4ca6-b39a-4507c2cd4ed0.png">

I copied one file to the root and added a link to it the .md file, it worked but the relative one didn't

<img width="1179" alt="Screenshot 2023-02-18 at 12 45 37 PM" src="https://user-images.githubusercontent.com/84435819/219847517-e616c55c-926c-47f6-a7dd-6036f89c1418.png">

again, there is a workaround, scripting files to move files from files inside to the root folder and and updating links

**Comment by secure-77** [comment] 2023-03-01 23:33
I need to test this but at least loading from a subfolder should work without any problems in my personal note I have all my images always in a subfolder of my current folder and this is working. Maybe there is an issue if the image is on a complete different path.

**Comment by berkgercek** [comment] 2023-03-08 21:44
Also having the same issue. Running the docker compose container system, and images in a separate folder (`assets/image.jpg`) are not loaded in. They do not appear in perlite nor in the files where they are linked.

**Comment by berkgercek** [comment] 2023-03-12 14:50
So I played around with this a bit and figured out what causes the break. 

The standard wikilinks-style shortcut for inserting an image, which you use in the demo repo, is e.g.
```
![[../assets/myimage.jpg]]
```
This works as expected even with relative file paths as above. However, obsidian prefers markdown-style syntax for images, which would refer the same image with optional alt text as follows:
```
![This is my image](../assets/myimage.jpg)
```

The latter syntax breaks image insertion in perlite and leads to a dead link, as it's attempting to resolve it as an http link

**Comment by secure-77** [comment] 2023-03-12 17:04
> So I played around with this a bit and figured out what causes the break.
> 
> The standard wikilinks-style shortcut for inserting an image, which you use in the demo repo, is e.g.
> 
> ```
> ![[../assets/myimage.jpg]]
> ```
> 
> This works as expected even with relative file paths as above. However, obsidian prefers markdown-style syntax for images, which would refer the same image with optional alt text as follows:
> 
> ```
> ![This is my image](../assets/myimage.jpg)
> ```
> 
> The latter syntax breaks image insertion in perlite and leads to a dead link, as it's attempting to resolve it as an http link

yes, "normal" markdown links are not supported, this is also the case for links to other files. You can change this setting in obsidian, see also the [requirements](https://github.com/secure-77/Perlite/wiki/03---Perlite-Settings#required-obsidian-settings)

**Comment by berkgercek** [comment] 2023-03-12 17:45
Okay, good to know. It might be good to add clarification on supported link types on the documentation then. Are footnotes also not supported?

**Comment by catrone3** [comment] 2023-04-14 19:30
Could this be from a pathing error? In the picture OP shared of the image not loading that pathing is for if the file loading the image in the root folder, notes in their case. However if the file trying to display the image is in a different location it would only look down with that pathing. It would need to go back to the root of the notes directory to load the image correctly.

**Comment by secure-77** [comment] 2023-04-15 08:33
Yes, I think the problem is that obsidian doesn't create relative paths for attachments, for internal links you can change it in the settings but for attachments it seems not to work, I will take close look to this soon but for the moment It seems attachments must be resident in the same or a subfolder for the current note location

**Comment by catrone3** [comment] 2023-04-20 20:34
if you have the setting of "New link format" to relative path to file, and have Automatically update internal links turned on. It seems to work for attachments. almost weekly I add new photos to my notes and move them around and they load just fine in the latest release of perlite.

**Comment by secure-77** [comment] 2023-04-29 15:27
I could figure it out, there are two different situation and behaviors.

 you can place a attachment in any directory you want and also move the attachment around. The link to the attachment should be then updated in you notes file and you will get a relative file path to the attachment, for example like this
`![[../../BASIC Tool Set/Pasted image 20211101013816.png]]`

the problem is when you move your notes file, then the path to the attachment will not be updated and will stay the same, in this case perlite can´t find the attachment anymore.

unfortunately I cant find any setting in perlite to auto update the path to the attachment after moving the file, so the only way to fix this, is then also move the attachment one time (to any directory you want) to get the link updated.


I will close this issue as I cant fix it and will add this to the wiki

**Closed by secure-77** 2023-04-29 15:27 UTC
Labels: bug report
