### ISSUE TITLE
Folder arrow marker randomly disappears

### ISSUE THREAD

**Issue by catrone3** [secure-77/Perlite#94] opened 2023-06-26 02:53 UTC
**Describe the bug**
When navigating through folders on the side bar, the arrows for folders occasionally disappear. 

**To Reproduce**
1. Click to open and close a folder

**Expected behavior**
The Arrows to not disappear

**Screenshots**
![image](https://github.com/secure-77/Perlite/assets/2140114/b75a685a-fdc7-409d-a34f-13b93978aa11)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome, opera
 - Version chrome version 114.0.5735.134

**Additional context**
This issue appears to just happen at random. no errors are appearing in the console on it.

**Comment by secure-77** [comment] 2023-07-28 08:45
I tried to trigger / reproduce the issue but without success. So its like impossible to fix it when I cant reproduce this. Can you please check your browser console when this occurs, best guess is that some JS error is thrown and break something.

**Comment by catrone3** [comment] 2023-10-22 23:53
The only error I am seeing in console is the following
![image](https://github.com/secure-77/Perlite/assets/2140114/231c4db0-cc23-4ce4-a7af-2d0cdcbf44d6)

If you would like to try and replicate it on my install I can send you a dm in discord with the url for it.

**Comment by secure-77** [comment] 2024-01-13 14:45
I finally find the bug (it was when you exactly click on the triangle) and fixed it, its on dev and will be in the next release

**Comment by secure-77** [comment] 2024-01-14 15:48
fixed / implemented in 1.5.8

**Closed by secure-77** 2024-01-14 15:48 UTC
Labels: implemented / fixed, confirmed bug, on dev
